const chartTypeConstant = {
  SAVE_CHART_TYPE: 'SAVE_CHART_TYPE',
  SAVE_CHART_TYPE_SUCCESS: 'SAVE_CHART_TYPE_SUCCESS',
  SAVE_CHART_TYPE_ERROR: 'SAVE_CHART_TYPE_ERROR',
  GET_TYPE_LIST: 'GET_TYPE_LIST',
  GET_TYPE_LIST_SUCCESS: 'GET_TYPE_LIST_SUCCESS',
  GET_TYPE_LIST_ERROR: 'GET_TYPE_LIST_ERROR'
};

module.exports = {
  chartTypeConstant
};